version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: afisha
      POSTGRES_USER: afisha
      POSTGRES_PASSWORD: 12345678
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-0}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
